#metrics: true

storage:
  type: sqlite
  path: /db/data.db

ui:
  title: 'Ergo Ecosystem Status'
  header: 'Ergo Ecosystem Status'
  logo: 'https://ergoplatform.org/img/uploads/1762.png'
  link: 'https://github.com/bdkent/ergo-status'
  buttons:
    - name: 'Join Alert Channel'
      link: 'https://t.me/ergo_status'
    - name: 'Contribute'
      link: 'https://github.com/bdkent/ergo-status'
    - name: 'Tips'
      link: 'https://explorer.ergoplatform.com/en/addresses/9fm5gUeTyNVMtB9AX4FCc4wPNtMxNryHS3YDP7Hn5mj7Corh4y8'

alerting:
  telegram: 
    token: ${ALERT_BOT_TOKEN}
    id: "-1001288637698" # ID of @ergo_status channel
    default-alert:
      enabled: true
      send-on-resolved: true

endpoints:

  - name: Homepage
    group: Ergo Platform
    url: "https://ergoplatform.org"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram


  - name: Explorer
    group: Ergo Platform
    url: "https://explorer.ergoplatform.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: API v0
    group: Ergo Platform
    url: "https://api.ergoplatform.com/api/v0/info"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: API v0 [testnet]
    group: Ergo Platform
    url: "https://api-testnet.ergoplatform.com/api/v0/info"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: API v1
    group: Ergo Platform
    url: "https://api.ergoplatform.com/api/v1/info"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: API v1 [testnet]
    group: Ergo Platform
    url: "https://api.ergoplatform.com/api/v1/info"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram


  - name: SigmaUSD App
    group: SigmaUSD
    url: "https://sigmausd.io"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: SigmaUSD Assembler
    group: SigmaUSD
    url: "https://assm.sigmausd.io/state"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].functioning == true"
    alerts:
      - type: telegram


  - name: ErgoDEX Homepage
    group: ErgoDEX
    url: "https://ergodex.io/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: ErgoDEX App
    group: ErgoDEX
    url: "https://app.ergodex.io/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram


  - name: Ergo Auction House App
    group: Ergo Auction House
    url: "https://ergoauctions.org"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: Ergo Auction House Assembler
    group: Ergo Auction House
    url: "https://assembler.ergoauctions.org/state"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].functioning == true"
    alerts:
      - type: telegram

  - name: Ergo Utils App
    group: Ergo Utils
    url: "https://ergoutils.org"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: Ergo Utils Assembler
    group: Ergo Utils
    url: "https://assembler.ergoutils.org/state"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].functioning == true"
    alerts:
      - type: telegram


  - name: Ergo Raffle (beta)
    group: Ergo Raffle
    url: "https://beta.ergoraffle.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram



  - name: Ergo Faucet [mainnet]
    group: Ergo Faucet
    url: "https://ergofaucet.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: Ergo Faucet [testnet]
    group: Ergo Faucet
    url: "https://testnet.ergofaucet.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram



  - name: ErgoPad 
    group: ErgoPad Faucet
    url: "https://ergopad.io"
    interval: 5m 
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram

