version: '3.9'
services:
  gatus:
    image: 'twinproduction/gatus'
    volumes:
      - './config.yaml:/config/config.yaml'
      - 'storage_data:/db'
    ports:
      - '8080:8080'

volumes:
  storage_data:
  