version: '3.9'

services:
  gatus:
    image: 'twinproduction/gatus'
    environment:
       ALERT_BOT_TOKEN: /run/secrets/ALERT_BOT_TOKEN
    volumes:
      - './config.yaml:/config/config.yaml'
      - 'storage_data:/db'
    ports:
      - '8080:80'

secrets:
  ALERT_BOT_TOKEN: 
    external: true

volumes:
  storage_data:
