version: '3.9'

services:
  gatus:
    image: 'twinproduction/gatus:v3.8.0'
    env_file:
      - vars.env
    volumes:
      - './config.yaml:/config/config.yaml'
      - 'storage_data:/db'
    ports:
      - '80:8080'

volumes:
  storage_data:
